# Generated by Django 3.2.6 on 2021-08-13 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='profile_image',
            field=models.TextField(blank=True),
        ),
    ]
