# Generated by Django 3.2.6 on 2021-08-13 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='profile_image',
        ),
    ]
