# Generated by Django 3.2.6 on 2021-08-13 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0004_comment_writer'),
        ('firstapp', '0005_auto_20210814_0159'),
    ]

    operations = [
    ]
